import type { Timestamp } from 'firebase/firestore';

/**
 * Represents the type of notification.
 */
export type NotificationType =
  | 'work_order_assigned'
  | 'work_order_status_change'
  | 'work_order_due'
  | 'estimate_approved'
  | 'estimate_rejected'
  | 'invoice_due'
  | 'invoice_paid'
  | 'inventory_low_stock'
  | 'timesheet_pending_approval'
  | 'timesheet_rejected'
  | 'maintenance_due'
  | 'new_message' // For chat
  | 'system_announcement'
  | 'deficiency_reported'
  | 'mention'; // User mentioned in notes/chat

/**
 * Represents a notification document in the 'notifications' Firestore collection.
 * These are typically generated by backend triggers or application logic.
 */
export interface Notification {
  id: string; // Firestore document ID
  company_id: string | null; // Null for platform-wide, company ID otherwise
  user_id: string; // The recipient user ID
  type: NotificationType;
  title: string; // Short title of the notification
  message: string; // Detailed message content
  is_read: boolean; // Whether the user has read the notification
  read_at?: Timestamp | null; // Firestore Timestamp
  created_at: Timestamp; // Firestore Timestamp
  related_entity_type?: string | null; // e.g., 'work-order', 'invoice'
  related_entity_id?: string | null; // ID of the related document
  link_url?: string | null; // Optional URL to navigate to when clicked
  // Optional: Add sender information if relevant
  // sender_id?: string | null;
  // sender_name?: string | null;
}
