

export const COLLECTIONS = {
    USERS: 'users',
    COMPANIES: 'companies',
    ROLES: 'roles',
    USER_ROLES: 'user_roles',
    CUSTOMERS: 'customers',
    LOCATIONS: 'locations',
    WORK_ORDERS: 'work_orders',
    EQUIPMENT: 'equipment',
    DEFICIENCIES: 'deficiencies',
    REPAIRS: 'repairs',
    INVENTORY: 'inventory_items', // Updated collection name for clarity
    PURCHASE_ORDERS: 'purchase_orders',
    ESTIMATES: 'estimates',
    INVOICES: 'invoices',
    MAINTENANCE_CONTRACTS: 'maintenance',
    CHECKLIST_TEMPLATES: 'checklist_templates',
    CHECKLIST_INSTANCES: 'checklist_instances',
    TIME_ENTRIES: 'time_entries',
    PAYROLL: 'payroll',
    REPORTS: 'reports',
    FILES: 'files',
    CHATS: 'chats',
    AUDIT_LOGS: 'audit_logs',
    PLATFORM_SETTINGS: 'platform_settings',
    COMPANY_MODULES: 'company_modules',
    WORKFLOW_STATUSES: 'workflow_statuses',
    WORKFLOW_TRIGGERS: 'workflow_triggers',
    NOTIFICATIONS: 'notifications',
    MODULES: 'modules',
    TODOS: 'todos',
};
